name: Deploy to WordPress.org
on:
  push:
    paths:
      - 'tags/**'
  
  workflow_dispatch:
    
jobs:
  tag:
    name: Push to tags
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: formitable-development-kit
